### ISSUE TITLE
Project creation - directory does not exist

### ISSUE THREAD

**Issue by NIHRBC** [jbohnslav/deepethogram#13]
```
Traceback (most recent call last):
  File "/data/$user/conda/envs/degram/lib/python3.7/site-packages/deepethogram/gui/main.py", line 640, in _new_project
    labeler)
  File "/data/$user/conda/envs/degram/lib/python3.7/site-packages/deepethogram/projects.py", line 46, in initialize_project
    assert os.path.isdir(directory), 'Directory does not exist: {}'.format(directory)
AssertionError: Directory does not exist: \data\$user\deepethogram

```
Issue:  When creating a project from the GUI, the above error occurs.  It meet the same error on any directory I try and I'm able to access those directories via other means within the session.  I'm guessing the issue stems from running remotely on the HPC cluster here, but I'm just not seeing the cause.

I feel extraordinarily dim for not being able to immediately solve this, but the changes I've made don't seem to be resolving the issue.

**Comment by jbohnslav** [comment]
Hmm, this is a bug that I can't easily replicate, because I don't have access to your cluster. However, something is clearly the matter, because in the string you posted, `$user` should be replaced with your username, e.g. `\data\NIHRBC\deepethogram`. 

Two solutions: you could `rsync` your videos to your local directory and label them there, and then transfer back to the cluster for model training. However, this is cumbersome. 

Another solution: make a folder yourself, e.g. `mkdir \data\NIHRBC\deepethogram`. CD: `cd \data\NIHRBC\deepethogram`. Then, when in that directory, run `deepethogram`. That way, it should automatically check if the current directory is a project directory with `os.getcwd()`, which shouldn't have that `$user` bug.

**Comment by NIHRBC** [comment]
Oh, sorry for the confusion - ignore the $user issue.  I'd amended the output to generalize it (and make sure I don't run afoul of our HPC IT guys with username sharing...pretty strict around here).  This isn't a bug or error, just poor communication on my end.

I'd messed around with it further - note the backslashes in the directory path `\data\NIHRBC\deepethogram`.  The cluster is obviously looking for forward slashes here and I'm not sure why the `os` isn't being smart enough to return those.  I attempted to force the change at a few different points but was unsuccessful.

I noted in the closed issues a Mac user that was throwing the same error using the pip installation and resolved the issue by installing from source.  This solution worked for me in resolving the issue.
