### ISSUE TITLE
CLI Inference Error

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#54]
Hi John.

Thanks for the new update. For CLI inference, I tried 

python -m deepethogram.feature_extractor.inference project.config_file=/mmfs1/data/wangccy/Trial_deepethogram/project_config.yaml
feature_extractor.weights=/data/wangccy/Trial_deepethogram/models/210511_124558_feature_extractor_train_None/checkpoint.pt flow_generator.weights=/data/wangccy/Trial_deepethogram/models/210510_153553_flow_generator_train_None/checkpoint.pt

I got the following error
<img width="1215" alt="Screen Shot 2021-05-25 at 10 36 35 PM" src="https://user-images.githubusercontent.com/46662361/119594375-aaf15f00-bda9-11eb-97d1-b0b76c550108.png">

Let know if I miss anything for the CLI inference. 

Thanks,

**Comment by jbohnslav** [comment]
Hmm. The problem is that PyTorch can't load your `.pt` file; it has an OmegaConf DictConfig in it (apparently) and it doesn't work with the new version of OmegaConf needed for DeepEthogram 0.1. Did you use your own code to save the model previously? There shouldn't be any OmegaConf configs in your `.pt` file. 

I see two solutions: 
* re-train new models with version 0.1 (has various improvements anyway). The new version (for sure) does not save any OmegaConf information in the state_dict. 
* temporarily downgrade OmegaConf to version `1.xx` from 2.0+, load the .pt file, and save only the weights to a new file. Then you can upgrade your OmegaConf again, and load the checkpoint file that only has weights in it. You can do that with an example like this: 
```python
# will have keys epoch, state_dict, optimizer, and hyperparameters. 
# 'hyperparameters' is the key with the erroneous OmegaConf configuration in it
state = torch.load('path/to/my/checkpoint.pt')
# get model params only
weights = state['state_dict']
# save model params only to new file
torch.save({'state_dict': weights}, 'path/to/my/checkpoint_weightsonly.pt')
```

**Comment by Jeffwang87** [comment]
Thanks! I am in the process of retraining the feature extractor, but encounter an another issue. Will open a new issue
