### ISSUE TITLE
Training Feature Extractor Invalid Loss

### ISSUE THREAD

**Issue by Jeffwang87** [jbohnslav/deepethogram#55]
Hi John,

I am training the feature extractor using the updated code. I encountered the invalid loss, and here is the screenshot
<img width="733" alt="Screen Shot 2021-05-28 at 6 48 49 PM" src="https://user-images.githubusercontent.com/46662361/120048528-589c8200-bfe5-11eb-9d37-a04c6bccb48b.png">
<img width="1305" alt="Screen Shot 2021-05-28 at 6 50 20 PM" src="https://user-images.githubusercontent.com/46662361/120048613-90a3c500-bfe5-11eb-8da4-9f9233fd07ac.png">

The training example is a video with two labels, one is background and another one is picking flowers. I labeled all the frames as picking flowers.

Please let me know what is the issue here. 

Thanks

**Comment by jbohnslav** [comment]
I was able to reproduce this issue. It should be fixed in bce16c902317cde615e99dfb51e6f30e8f4c73a1. Please `pip install --upgrade deepethogram` to 0.1.1 to see if that fixes things. 

Note: if you have all examples of 1 class and no negative examples, the model probably will not learn anything. It will only learn to predict 1s all the time. So I'd definitely recommend adding another video with some negative examples.
