### ISSUE TITLE
When to finalize labels and import predictions to correct and retrain models

### ISSUE THREAD

**Issue by edgarbc** [jbohnslav/deepethogram#65]
Hi,

I am a bit confused about the pipeline for how to re-train the models. I have read the paper and the use-guide and followed these steps using the GUI:
1. Manually labeled 3 videos
2. Train FlowGenerator
3. Train and Infer FeatureExtractor
4. Train and Infer Sequence

I can compare the manually labeled vs predicted behaviors in a video. I am not sure when to finalize labels and when to load predictions as labels to retrain the models. In particular,

1. When to press Finalize labels?
2. Once I produce the predictions should I import them as labels and then correct the errors and save and re-train?
3. What models do I re-train with the corrected labels? Only the Sequence model?
4. Should I repeat 1-3 every time I load a new video for prediction (assuming I want to keep improving the models)?

Thank you!

**Comment by jbohnslav** [comment]
1. You "finalize labels" whenever you are done labeling the video. The reason that "finalize labels" exists is so that you do not have to affirmatively label every single frame with no behavior as "background"; that's what the button does. 
2. Yes, that's correct. You should import them as labels and fix them. 
3. You can train any model you want with the corrected labels; you might have more success re-training the feature extractor than the sequence model, but it will take longer. 
4. Yes, every time you add new data. I kind of assumed people would do this in batches rather than one video at a time. 

If you have more questions, feel free to re-open!
